// <auto-generated />
#region License
// MIT License
// 
// Copyright (c) Daniel Cazzulino
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
#endregion

#nullable enable
using System;
using System.Diagnostics;

namespace System
{
    /// <summary>
    /// Provides a high-precision (down to a tenths of microseconds) 
    /// <see cref="DateTimeOffset"/> value for <see cref="UtcNow"/>.
    /// </summary>
    static partial class PreciseTime
    {
        static readonly long startTimestamp = Stopwatch.GetTimestamp();
        // We just preserve milliseconds precision from DateTimeOffset, which is precise enough for 
        // adding the timestamps on top.
        static readonly long startTicks = DateTimeOffset.UtcNow.Ticks / TimeSpan.TicksPerMillisecond * TimeSpan.TicksPerMillisecond;

        /// <summary>
        /// Gets the elapsed time since the initial usage of <see cref="PreciseTime"/>.
        /// </summary>
        public static TimeSpan Uptime => TimeSpan.FromTicks(GetUtcNowTicks() - startTicks);

        /// <summary>
        /// Gets the high-precision value of the current UTC date time, with 10.000.000ths of a 
        /// second precision (within the current process).
        /// </summary>
        public static DateTimeOffset UtcNow => new DateTimeOffset(GetUtcNowTicks(), TimeSpan.Zero);

        static long GetUtcNowTicks()
        {
            // Calculate the fractional elapsed seconds since we started
            double elapsedTicks = (Stopwatch.GetTimestamp() - startTimestamp) / (double)Stopwatch.Frequency;
            // Discard milliseconds, which we're getting from DateTimeOffset.UtcNow ticks
            double microsecTicks = (elapsedTicks * 1000) - (int)elapsedTicks * 1000;

            return startTicks + (long)(microsecTicks * 10000);
        }
    }
}
